newsx/account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

newsx/newsapp/urls.py
from django.conf.urls import url
from . import views


app_name = 'articles'

urlpatterns = [
    url(r'^$', views.newsitems, name = "items" ),
    url(r'^profile/$', views.user_profile, name="profile"),
    url(r'^(?P<slug>[\w-]+)/$', views.details, name = "detail" )
]

newsx/newsx/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from newsapp import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    url(r'^newsapp/', include('newsapp.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.newsitems, name="home"),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsx/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)
    dob = models.DateField(null=True, blank=True)

newsx/newsapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Article(models.Model):
    article_title = models.CharField(max_length=300)
    slug = models.SlugField()
    article_text = models.TextField()
    date_published = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.DO_NOTHING)
    

    def __str__(self):
        return self.article_title

    def snippet(self):
        return self.article_text[:50] + '...'

newsx/account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from dobwidget import DateOfBirthWidget



class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Insert a valid email address.')
    dob = forms.DateField(widget=DateOfBirthWidget)
    

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'dob',
            'email',
            'password1',
            'password2',
            )
    
    

newsx/newsapp/forms.py
from django import forms
from . import models

class AddArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['article_title', 'slug', 'article_text', 'thumb' ]
        

newsx/account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from .forms import RegistrationForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User

# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.dob = form.cleaned_data.get('dob')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('home')
    else:
        form = RegistrationForm()
    return render(request, 'account/signup.html', {'form': form })

def account_activation_sent(request):
    return render(request, 'account/account_activation_sent.html')

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.profile.email_confirmed = True
        user.save()
        login(request, user)
        return redirect('home')
    else:
        return render(request, 'account_activation_invalid.html')

def login_view(request):
    if request.method == 'POST':
        form =AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:items')
    else:
        form = AuthenticationForm()
    return render(request, 'account/login.html', {'form':form })

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:items')

newsx/newsapp/views.py
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def newsitems(request):
    articles = Article.objects.all().order_by('date_published')
    return render(request, 'newsapp/newsitems.html', {'articles': articles})

def details(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'newsapp/detail.html', {'article' : article})

@login_required(login_url="/account/login/")
def user_profile(request):
    if request.method == 'POST':
        form = forms.AddArticle(request.POST,request.FILES)
        if form.is_valid():
            savetouser = form.save(commit=False)
            savetouser.author = request.user
            savetouser.save()
            return redirect('articles:items')
    else:
        form = forms.AddArticle()
    return render(request, 'newsapp/profile.html', {'form': form})

newsx/newsx/views.py
from django.http import HttpResponse
from django.shortcuts import render

def home(request):
    #return HttpResponse('home')
    return render(request, 'index.html')

def about(request):
    #return HttpResponse('about')
    return render(request, 'about.html')

newsx/newsapp/templates/newsapp/detail.html
{% extends 'base.html'%}

{% block content %}

<div class="detail">

    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{article.article_title}}</h2>
        <p>{{article.article_text}}</p>
        <p>{{article.date_published}}</p>

    
    </div>



</div>


{% endblock %}

newsx/newsapp/templates/newsapp/newsitems.html
 {% extends 'base.html' %}
    {% block content %}
        <h1>In Today's News</h1>

            <div class="articles">

                {% for article in articles %}
                    <div class="article">
                        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.article_title }}</a></h2>
                        <p>{{ article.article_text }}</p>
                        <p>{{ article.date_published }}</p>
                        <p>{{ article.author }}</p>
                    
                    </div> 



                {% endfor %}
            </div>

   {% endblock %}

newsx/newsapp/templates/newsapp/profile.html
{% extends 'base.html' %}

{% block content %}

    <div class="user-profile">
        <h2>Add New Article</h2>
        <form class="site-form" action="{% url 'articles:profile' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Add">
        </form>

    </div>
    <script src="/static/slugify.js"></script>

{% endblock %}

newsx/templates/about.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>About</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>

newsx/templates/base.html
{% load static %}

<!doctype html>

<html>

  <head>
    <meta charset="utf-8">
    <title>{% block title %}Index{% endblock title %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    {% block stylesheet %}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    {% endblock stylesheet %}
  </head>

  <body class="wrapper">
    
      
        <header>

            <h1><a href="{% url 'home'%}"><img src="{% static 'img/logo.png'%}" /></a></h1>

                <nav>
                  <ul>
                    {% if user.is_authenticated %}
                    <li>
                      <form class="logout" action="{%url 'account:logout'%}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                      </form>
                    </li>
                    <li><a href="{% url 'articles:profile' %}" class="highlight">Add New Article</a></li>
                    {% else %}
                      <li><a href="{% url 'account:login' %}">Login</a></li>
                      <li><a href="{% url 'account:signup' %}">SignUp</a></li>
                    {% endif %}
                  </ul>
                </nav>
                

          </header>

                <main>
                  {% block content %}


                  
                  {% endblock content %}
                </main>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% block javascript %}
    {% endblock javascript%}
  </body>
</html>

newsx/templates/index.html
    {% extends 'base.html' %}
    
        {% block content %}

            <h1>Home</h1>

        {% endblock %}
    